entity_threshold: 100
time_decay:
  half_life_hours: 24.0
  floor: 0.2
impact_weight_map:
  low: 0.8
  med: 1.0
  high: 1.2
  crown: 1.5
criticality_multiplier_map:
  low: 1.0
  med: 1.1
  high: 1.3
  crown: 1.6
vulnerable_multiplier: 1.25
